// Generated by gencpp from file learing_topic/person.msg
// DO NOT EDIT!


#ifndef LEARING_TOPIC_MESSAGE_PERSON_H
#define LEARING_TOPIC_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learing_topic
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : name()
    , sex(0)
    , age(0)  {
    }
  person_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , sex(0)
    , age(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _sex_type;
  _sex_type sex;

   typedef uint8_t _age_type;
  _age_type age;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknow)
  #undef unknow
#endif
#if defined(_WIN32) && defined(male)
  #undef male
#endif
#if defined(_WIN32) && defined(female)
  #undef female
#endif

  enum {
    unknow = 0u,
    male = 1u,
    female = 2u,
  };


  typedef boost::shared_ptr< ::learing_topic::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learing_topic::person_<ContainerAllocator> const> ConstPtr;

}; // struct person_

typedef ::learing_topic::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::learing_topic::person > personPtr;
typedef boost::shared_ptr< ::learing_topic::person const> personConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learing_topic::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learing_topic::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learing_topic::person_<ContainerAllocator1> & lhs, const ::learing_topic::person_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.sex == rhs.sex &&
    lhs.age == rhs.age;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learing_topic::person_<ContainerAllocator1> & lhs, const ::learing_topic::person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learing_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learing_topic::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learing_topic::person_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learing_topic::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learing_topic::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learing_topic::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learing_topic::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learing_topic::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "612b7faf5bf6954824ea814f6f846838";
  }

  static const char* value(const ::learing_topic::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x612b7faf5bf69548ULL;
  static const uint64_t static_value2 = 0x24ea814f6f846838ULL;
};

template<class ContainerAllocator>
struct DataType< ::learing_topic::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learing_topic/person";
  }

  static const char* value(const ::learing_topic::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learing_topic::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"uint8  sex\n"
"uint8  age\n"
"\n"
"uint8 unknow = 0\n"
"uint8 male = 1\n"
"uint8 female = 2\n"
;
  }

  static const char* value(const ::learing_topic::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learing_topic::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.sex);
      stream.next(m.age);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learing_topic::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learing_topic::person_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "sex: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sex);
    s << indent << "age: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.age);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARING_TOPIC_MESSAGE_PERSON_H
