// Generated by gencpp from file learing_service/personResponse.msg
// DO NOT EDIT!


#ifndef LEARING_SERVICE_MESSAGE_PERSONRESPONSE_H
#define LEARING_SERVICE_MESSAGE_PERSONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learing_service
{
template <class ContainerAllocator>
struct personResponse_
{
  typedef personResponse_<ContainerAllocator> Type;

  personResponse_()
    : result()  {
    }
  personResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::learing_service::personResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learing_service::personResponse_<ContainerAllocator> const> ConstPtr;

}; // struct personResponse_

typedef ::learing_service::personResponse_<std::allocator<void> > personResponse;

typedef boost::shared_ptr< ::learing_service::personResponse > personResponsePtr;
typedef boost::shared_ptr< ::learing_service::personResponse const> personResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learing_service::personResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learing_service::personResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learing_service::personResponse_<ContainerAllocator1> & lhs, const ::learing_service::personResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learing_service::personResponse_<ContainerAllocator1> & lhs, const ::learing_service::personResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learing_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::learing_service::personResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learing_service::personResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learing_service::personResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learing_service::personResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learing_service::personResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learing_service::personResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learing_service::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::learing_service::personResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::learing_service::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learing_service/personResponse";
  }

  static const char* value(const ::learing_service::personResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learing_service::personResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::learing_service::personResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learing_service::personResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct personResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learing_service::personResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learing_service::personResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARING_SERVICE_MESSAGE_PERSONRESPONSE_H
