// Generated by gencpp from file learing_service/person.msg
// DO NOT EDIT!


#ifndef LEARING_SERVICE_MESSAGE_PERSON_H
#define LEARING_SERVICE_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <learing_service/personRequest.h>
#include <learing_service/personResponse.h>


namespace learing_service
{

struct person
{

typedef personRequest Request;
typedef personResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct person
} // namespace learing_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::learing_service::person > {
  static const char* value()
  {
    return "c198113e7dd9cc5c9fd5f271c8479b39";
  }

  static const char* value(const ::learing_service::person&) { return value(); }
};

template<>
struct DataType< ::learing_service::person > {
  static const char* value()
  {
    return "learing_service/person";
  }

  static const char* value(const ::learing_service::person&) { return value(); }
};


// service_traits::MD5Sum< ::learing_service::personRequest> should match
// service_traits::MD5Sum< ::learing_service::person >
template<>
struct MD5Sum< ::learing_service::personRequest>
{
  static const char* value()
  {
    return MD5Sum< ::learing_service::person >::value();
  }
  static const char* value(const ::learing_service::personRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::learing_service::personRequest> should match
// service_traits::DataType< ::learing_service::person >
template<>
struct DataType< ::learing_service::personRequest>
{
  static const char* value()
  {
    return DataType< ::learing_service::person >::value();
  }
  static const char* value(const ::learing_service::personRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::learing_service::personResponse> should match
// service_traits::MD5Sum< ::learing_service::person >
template<>
struct MD5Sum< ::learing_service::personResponse>
{
  static const char* value()
  {
    return MD5Sum< ::learing_service::person >::value();
  }
  static const char* value(const ::learing_service::personResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::learing_service::personResponse> should match
// service_traits::DataType< ::learing_service::person >
template<>
struct DataType< ::learing_service::personResponse>
{
  static const char* value()
  {
    return DataType< ::learing_service::person >::value();
  }
  static const char* value(const ::learing_service::personResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LEARING_SERVICE_MESSAGE_PERSON_H
